# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
